name: geiger_edu
description: GEIGER-EDU project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version number for the application.
version: 1.0.20210906+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_html: ^2.1.0
  html: ^0.15.0
  webview_flutter: ^2.0.9
  flutter_inappwebview: ^5.3.2

  #connectivity
  connectivity: ^3.0.6

  #chat
  flutter_chat_ui: ^1.1.9
  #chat utils
  file_picker: ^3.0.4
  image_picker: ^0.8.2
  path_provider: ^2.0.2

  #Hive database
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  hive_listener: ^1.2.1

  flutter_svg: ^0.22.0  # to load svg images
  string_validator: ^0.3.0
  page_view_indicators: ^2.0.0
  get: ^4.3.0
  cron: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

    #hive database generators
  build_runner: ^1.12.2
  hive_generator: ^1.0.1

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/img/profile/
    - assets/img/splashscreen/
    - assets/img/loadingcircle/
    - assets/img/indicator/
    - assets/img/categories/
    - assets/lesson/
    - assets/lesson/password/
    - assets/lesson/password/password_safety/
    - assets/lesson/password/password_safety/eng/
    - assets/lesson/password/password_safety/eng/img/
    - assets/lesson/password/password_safety/ger/
    - assets/lesson/password/password_safety/ger/img/

  # To add custom fonts to the application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
